const themes=[['sunshine','Sunshine Club'],['festival','Rally Festival'],['toybox','Toybox Arena']];
const states=[['home','Home menu'],['sports','Choose a sport'],['loading','Loading'],['flyover','Drone flyover'],['rally','Active rally'],['serve','Your serve'],['pause','Pause menu'],['results','Match results']];
const btn=(s,secondary=false)=>`<button class="btn ${secondary?'secondary':''}">${s}</button>`;
const brand='<span class="brand">ISLAND<br>SPORTS CLUB</span>';
const topbar=(right)=>`<div class="top">${brand}<span class="pill">${right}</span></div>`;
const hero=(label='ADNAN / YOUR ATHLETE')=>`<div class="hero-card"><img src="assets/hero.png" alt="Actual V4 character render"><div class="hero-label">${label}</div></div>`;
const score=()=>`<div class="scorebug"><div class="scorehead">TROPICAL OPEN / SET 1</div><div class="scoreline"><span>ADNAN</span><i class="serve-dot"></i><b>2</b><strong>30</strong></div><div class="scoreline"><span>RILEY</span><i></i><b>1</b><strong>15</strong></div></div><button class="btn secondary pause" aria-label="Pause match">Ⅱ</button>`;
function render(t,s){let body='',game=['rally','serve','pause','flyover'].includes(s);const base=`<div class="arches"></div><div class="floor"></div>`;
if(s==='home')body=`<img class="bg" src="assets/home.jpg"><div class="menuwash"></div>${base}<div class="safe">${topbar('● TV connected')}${hero()}<div style="position:absolute;top:145px;width:650px"><div class="kicker light">WELCOME BACK, ADNAN</div><h1 class="headline" style="margin:22px 0 34px">GOOD TIMES.<br><em>GREAT GAMES.</em></h1><div class="stack" style="width:455px">${btn('LET’S PLAY <span>→</span>')}<div class="row">${btn('Campaign',true)}${btn('Your locker',true)}</div></div></div><div class="foot light"><span>☀ Your island. Your game.</span><span>Settings ⚙ &nbsp; · &nbsp; Phone connected</span></div></div>`;
if(s==='sports')body=`${base}<div class="safe">${topbar('CHOOSE A SPORT')}<h1 class="headline" style="font-size:68px;margin:38px 0 36px">WHAT’S THE <em>GAME?</em></h1><div class="cardgrid"><button class="panel sport" data-next="loading"><img src="assets/club-tennis.png"><h2>Tennis <span>↗</span></h2><p>Quick match · Campaign · Training</p></button><button class="panel sport" data-next="loading"><img src="assets/club-golf.png"><h2>Golf <span>↗</span></h2><p>Head out for a round.</p></button></div><div class="foot light"><span>← Back</span><span>Pick a sport on your phone</span></div></div>`;
if(s==='loading')body=`${base}<div class="safe">${topbar('TENNIS / TROPICAL OPEN')}${hero('YOUR EQUIPPED LOOK')}<div style="position:absolute;top:170px;width:650px"><div class="kicker light">NEXT UP / ONE MORE GREAT RALLY</div><h1 class="headline" style="margin:22px 0 35px">GOOD TIMES<br><em>AHEAD.</em></h1><div class="row" style="width:590px"><div class="meter" style="flex:1"><i></i></div><strong class="light" style="font-size:32px">72%</strong></div><p class="body light" style="margin-top:27px">Clean timing. More speed.</p></div><div class="foot light"><span>Warming up the court…</span><span>Your phone is the racket.</span></div></div>`;
if(s==='flyover')body=`<img class="bg" src="assets/flyover.png"><div class="safe"><span class="pill">ROUND 05 / TENNIS</span></div><div class="panel venue"><div class="kicker">WELCOME TO</div><h2>Tropical Open</h2><span style="font-size:20px">A little sun. A lot of game.</span></div><div style="position:absolute;right:64px;bottom:64px">${btn('Skip intro →',true)}</div>`;
if(s==='rally'||s==='serve'||s==='pause'){body=`<img class="bg" src="assets/gameplay.png">${score()}`;if(s==='rally')body+=`<div class="feedback"><strong>PERFECT!</strong><p>118 km/h · Clean timing</p></div>`;if(s==='serve')body+=`<div class="panel servebox"><div class="top"><h3>Your serve</h3><span class="pill" style="font-size:14px">1st</span></div><p style="font-size:17px;margin-top:13px">Swing when the marker hits the target.</p><div class="track"></div><div class="top" style="font-size:14px;font-weight:800"><span>EARLY</span><span>LATE</span></div></div>`;if(s==='pause')body+=`<div class="veil"></div><div class="panel modal"><div class="kicker">TAKE A BREATHER</div><h2>Paused.</h2><div class="stack">${btn('Back to the court →')}${btn('Sound & controls',true)}${btn('Exit to menu',true)}</div><p style="font-size:16px;margin-top:25px;text-align:center">Your match is paused.</p></div>`;}
if(s==='results')body=`${base}<div class="safe">${topbar('MATCH COMPLETE')}${hero('WINNER / ADNAN')}<div style="position:absolute;top:135px;width:650px"><div class="kicker light">TROPICAL OPEN / VICTORY</div><h1 class="headline" style="margin-top:20px">THAT’S<br><em>A WIN.</em></h1><div class="resultnum light">6 — 4</div><p class="body light">Adnan defeats Riley.</p><div style="margin-top:26px;width:460px" class="stack">${btn('NEXT ROUND <span>→</span>')}<div class="row">${btn('Replay',true)}${btn('Exit to menu',true)}</div></div></div><div class="foot light"><span>View rewards ↗</span><span>Tap an action on your phone.</span></div></div>`;
return `<div class="frame ${t} state-${s} ${game?'game':''}">${body}${game?'':'<div class="texture"></div>'}<div class="statusfoot">UI MOCKUP · EXISTING REPO CAPTURES · SAMPLE VALUES</div></div>`;}
let theme=0,state=0;const q=new URLSearchParams(location.search);if(q.has('theme'))theme=Number(q.get('theme'));if(q.has('screen'))state=Number(q.get('screen'));const stage=document.querySelector('.stage');
function show(){stage.innerHTML=render(themes[theme][0],states[state][0]);document.querySelectorAll('#themes button').forEach((b,i)=>b.setAttribute('aria-pressed',i===theme));document.querySelectorAll('#states button').forEach((b,i)=>b.setAttribute('aria-pressed',i===state));document.querySelector('.caption').textContent=`${themes[theme][1]} / ${states[state][1]} — Actual repo imagery with proposed UI. These are browser mockups, not Unity screenshots of an implemented redesign. Character and court remain unchanged.`;stage.querySelectorAll('button').forEach(b=>b.onclick=()=>{if(b.dataset.next){state=2;show();return;}const x=b.innerHTML;b.innerHTML='Preview only';setTimeout(()=>b.innerHTML=x,600)});}
for(const [id,list,set] of [['themes',themes,i=>theme=i],['states',states,i=>state=i]])list.forEach((v,i)=>{const b=document.createElement('button');b.textContent=(id==='themes'?`${i+1}. `:'')+v[1];b.onclick=()=>{set(i);show()};document.getElementById(id).append(b)});
if(q.has('capture'))document.body.className='capture';function fit(){if(!q.has('capture')){stage.style.zoom=Math.min(1,(innerWidth-40)/1280);document.querySelector('.caption').style.width=Math.min(1280,innerWidth-40)+'px';}}window.addEventListener('resize',fit);show();fit();
