"""hole09_build.py - Hole 9 "Split" (par 5, 494 yd): a C-shaped ring island at ONE height (6 m), LOOK build (POSTCARD_LOOK CONTINUE).

Run from a clean Blender (re-runnable, deterministic: every random draw is seeded):

    /Applications/Blender.app/Contents/MacOS/Blender -b --factory-startup --python blender/scripts/hole09_build.py -- --out DIR [--no-render] [--no-qa]

    --out DIR     write hole_09.blend, hole_09_overview.png, hole_09.fbx (+ a fresh .fbx.meta) into DIR instead of the repo paths.
                  The staging runs of the CONTINUE job always use it (work/postcard-look/v2/hole09/stage); without it the script writes
                  blender/hole_09.blend, blender/previews/hole_09_overview.png and Unity/Assets/Resources/Course/hole_09.fbx (the INSTALL).
    --no-render   skip the EEVEE overview render
    --no-qa       skip the in-build gates (faster iteration)

The scoring build is UNCHANGED (postcard_lib: terrain, play surfaces, gameplay, one ocean plane); the previous flat decoration (foot / face /
rim icosahedra, ROCK_STACK_nn columns, rock-boulder ruin walls, WATER_FOAM strips) is gone. The look pass (the order of the brief):

    scoring build -> look_materials -> snapshot_ground -> retarget_materials -> LK_SCRUB on the ridge top (a material; the lie stays Rough)
      -> scenery (hole09_look.build_scenery: sea stacks, masonry ruin + broken arch (hole09_masonry: irregular rubble stones, REPAIR ROUND 1), rocks, crag groups, DRESS_KNOLL hummocks, the shrub / rock chain
      over the scrub boundary, shrub thickets / tufts / flowers) -> chipped masonry blocks -> DRESS_SAND lobes on the bunker lips -> cliff skin (strata) -> sea (thin shelf, sparse surf) -> assign_uvs LAST -> compare_ground -> audits -> render -> save ->
      postcard_look_lib.export_look_fbx (NEVER postcard_lib.export_fbx).

REPAIR ROUND 1 (2026-10-04, after the third review): the ruin is rebuilt from irregular chipped stones (hole09_masonry.py: buried first course, support-checked courses, a lintel stone bearing on both
jambs, a broken voussoir arch facing the landmark camera, a rubble heap in the arch gap); TEE_BOX is LK_FAIRWAY (no seam against the ribbon); the libs / textures were regenerated by the shared fixers.

REPAIR ROUND 2 (2026-10-05, review "the ruin still reads as stacked bricks"): hole09_masonry.py is rewritten (flat-shaded rough stones, brick-interior UV windows, skyline rubble on wavy bed levels, ragged tops, the
broken arch seated in both piers with one crown wedge missing) and hole09_look.chip_blocks gives the fallen blocks rough rounded variants; this file only gets this note (the shared fixers regenerated libs / textures again).

ROUND 3 (2026-10-04, second skeptic review): only the cliff skin parameters (SKIN_*) changed here; the knoll shape change is in hole09_look.py (_knoll_mesh).

REPAIR ROUND 3 of the CONTINUE job (2026-10-05): (1) the ruin / arch are planar-faced stones (hole09_stone.py, hole09_masonry.py, hole09_look.py: the 'triangle-split' shading of the review was hull faces split into
triangles with independent UV windows); (2) the TEE_BOX plate (10 cm over the fairway, no riser) hid 0.48 m of fairway behind its far edge from the address camera, a texture jump across the whole frame width
('a faint straight ruler line', rows 556 / 557): tee_parallax_uvs() scales the plate's UVs 4.4 % about the camera (tools/tee_parallax_check.py: 0.49 m -> 0.002 m); (3) the blend is saved with relative_remap=False
(proof pass: LK_TEXTURED@blend failed on the installed blender/hole_09.blend). The triangle budget was met by 132 -> 116 ridge shrubs (the shared props library's shrub meshes grew +3.9k triangles).

GRASS + RUIN PASS (2026-10-05, CONTINUE job phase 3, repair round 0): hole09_look.build_scenery ends with build_grass() (the edge fringe, the cheapened old tufts, the ruin-scrub clump field, wall-foot tufts and bush skirts; every PLANT_
carries the sway vertex colours of the new props library, exported by export_look_fbx as before: colors_type LINEAR), the masonry gets rounder, chunkier stones and a slipped (not missing) keystone. SKIN_STEP_M is
unchanged (a larger step does nothing: the strata columns follow the TERRAIN outline vertices, which are closer than 2.4 m). Triangles 247,439 -> see INSTALL.md (<= 250,000).

GOAL15 PHASE3: hole09_look.build_split_cliff replaces the old cladding with four unequal eroded beds, deeper overhangs/undercuts and short irregular headlands.
Ridge scenery has taller narrow scrub slopes and bare-rock crests inside the same safe footprints. Whole chipped masonry stones are batched after the plant/root placements,
with material submeshes preserved. Far-field filler budgets fund the cliff geometry; the tee, approach and ruin fringe budgets remain unchanged. Scoring geometry stays frozen.

The design file hole09_design.py is untouched (course data, shore, hazards, pin, SCENERY): `python3 blender/scripts/postcard_emit_cs.py --check
Unity/Assets/Scripts/Course/Hole.cs` must still say no drift. Gate it with postcard_look_verify.py 9 (+ postcard_verify.py, whose MATERIALS /
WATER_LEVEL / FBX_BUDGET lines fail by design on an LK_* build, see work/postcard-look/v2/hole09/GATES_hole09.txt).
"""
import math
import json
import os
import sys
import time

sys.dont_write_bytecode = True
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import numpy as np                                   # noqa: E402
import bpy                                           # noqa: E402
from mathutils import Matrix, Vector                 # noqa: E402

import postcard_lib as P                             # noqa: E402
import postcard_look_lib as L                        # noqa: E402
import postcard_props_lib as PL                      # noqa: E402
import hole09_look as HL                             # noqa: E402

YD = P.YD
TEE_BOX_M = (10.4, 13.2)      # design 12 x 16 yd; the largest rounded rectangle that stays inside the 9 yd fairway round end
TEE_CAM_BACK_YD, TEE_CAM_UP_YD = 4.5, 2.46   # round 3: the address camera of a tee shot (CameraRig.FrameAddress): 4.5 yd behind the ball, 2.4 yd + the 0.06 yd ball height over the tee top (tools/tee_parallax_check.py)

ARGS = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []


def opt(name, default=None):
    return ARGS[ARGS.index(name) + 1] if name in ARGS and ARGS.index(name) + 1 < len(ARGS) else default


OUT = os.path.abspath(opt("--out")) if opt("--out") else None
RENDER = "--no-render" not in ARGS
QA = "--no-qa" not in ARGS
GATES = []


def gate(name, ok, detail):
    GATES.append((name, bool(ok), str(detail)))
    print(f"GATE: {name} {'PASS' if ok else 'FAIL'} - {detail}", flush=True)


# ----------------------------------------------------------------------------------------------- overview framing
def frame_overview(D, rot_deg=(50.0, 0.0, 20.0), margin=1.06, height_px=1700):
    """CAM_HOLE_OVERVIEW like the lib (orthographic, same angle as hole 7) but framed for a tall thin island: the image is
    as wide as the island's projection needs instead of the lib's square 1:1 frame. Returns the (width, height) in pixels."""
    cam = bpy.data.objects["CAM_HOLE_OVERVIEW"]
    rot = Matrix.Rotation(math.radians(rot_deg[2]), 3, 'Z') @ Matrix.Rotation(math.radians(rot_deg[0]), 3, 'X')
    right, up, view = rot @ Vector((1, 0, 0)), rot @ Vector((0, 1, 0)), rot @ Vector((0, 0, -1))
    corners = [Vector((x, y, z)) for x, y in (P.m(a, b) for a, b in D.SHORE) for z in (D.play_z + 10.0, -6.0)]
    rs = [c.dot(right) for c in corners]
    us = [c.dot(up) for c in corners]
    wr, hu = (max(rs) - min(rs)) * margin, (max(us) - min(us)) * margin
    cam.rotation_euler = rot.to_euler()
    cam.location = right * ((min(rs) + max(rs)) / 2) + up * ((min(us) + max(us)) / 2) - view * 1500.0
    res = (int(round(height_px * wr / hu / 2) * 2), height_px)
    cam.data.ortho_scale = max(wr, hu * res[0] / res[1]) if res[0] >= res[1] else hu
    return res


# ----------------------------------------------------------------------------------------------- build
t_start = time.time()
D = P.start("hole09_design", out_dir=OUT)
D.mod.SCENERY["tee_box_m"] = TEE_BOX_M                       # lib key: tee box width x depth in metres (set at runtime, not in the design file)

# 1. the scoring build (unchanged): flat top at PLAY_Z, banded cliffs, play surfaces, one ocean plane, gameplay placeholders, cameras
P.build_terrain(D)
P.build_play_surfaces(D)
P.build_water(D, shallow_material=None, foam_material=None)  # the ocean plane only: L.build_sea replaces it by the graded grid + thin shelf + sparse surf
P.build_gameplay(D)
P.build_cameras_and_light(D)

# 2. the look pass
L.look_materials(D)
snap = L.snapshot_ground(D)
L.retarget_materials(D)
# REPAIR ROUND 1 (finding 'straight seam across the tee frame'): the tee box was LK_GREEN (planar UV, no mow stripes) next to the LK_FAIRWAY ribbon (centerline UV, stripes), a ruler-straight step
# in grass tone. On LK_FAIRWAY the centerline UVs make the stripes run on under the tee ball. postcard_look_verify allows {LK_GREEN, LK_FAIRWAY} on TEE_BOX; the lie is Hole.LieAt (untouched).
tee_ob = bpy.data.objects["TEE_BOX"]
tee_ob.data.materials[0] = L.look_material("LK_FAIRWAY", D)
try:                                                          # shading only (vertices / faces untouched): the rim vertices of the 10 cm riser must not average the riser normal into the top face
    tee_ob.data.shade_smooth()
    tee_ob.data.set_sharp_from_angle(angle=math.radians(30.0))
except Exception as exc:                                      # pragma: no cover
    print("[hole09] tee box shading not changed:", exc)
tee_ob.data.update()
poly = HL.scrub_polygon_yd(D)
n_core, n_soft = HL.assign_scrub_soft(D, poly)                # the dry olive ridge: a material only (core polygon + a patchy soft zone), the lie stays Rough
n_scrub = n_core + n_soft
scn = HL.build_scenery(D)                                     # sea stacks, ruin, rocks, ridge outcrops + knolls, the shrub / rock chain over the scrub boundary, thickets, tufts
cover = scn["cover"]
n_chip, chip_verts = HL.chip_blocks(D)                        # round 2: the fallen ruin blocks / rubble get chipped meshes (>= 64 welded vertices, was 24)
sand_objs, sand_info = HL.build_sand_overlay(D)               # round 2: DRESS_SAND_nn lobes on the bunker lips (visual only)
PL.assert_no_legacy_rocks(D)                                  # raises if any icosahedron / < 60 vertex rock is left
skin = HL.build_split_cliff(D)                               # Goal15: actual eroded beds/overhangs on every frozen boundary edge; no scoring mutation
bpy.context.view_layer.update()                               # LIB BUG workaround: build_sea reads matrix_world of the rocks just placed (stale = identity until the view layer updates), see LIB_BUGS.md
L.build_sea(D)                                                # AFTER the skin and the rocks (it measures both); the channel gap is an automatic shelf pocket
L.retarget_materials(D)
L.assign_uvs(D)                                               # LAST
if OUT:
    checkpoint_dir = os.path.join(os.path.dirname(OUT), 'checkpoints')
    os.makedirs(checkpoint_dir, exist_ok=True)
    checkpoint = os.path.join(checkpoint_dir, 'unverified_pre_batch.blend')
    # Scratch recovery point only: no audits, export or acceptance claim.
    bpy.ops.wm.save_as_mainfile(filepath=checkpoint, relative_remap=False)
    with open(os.path.join(checkpoint_dir,'unverified_pre_batch.json'),'w') as handle:
        json.dump(dict(verified=False, reason='before static batching and unchanged audits',
                       scenery={k:[o.name for o in scn[k]] for k in ('ruin','shrubs','shrubs_out','agave','flowers','tufts')},
                       ridge_specs=[list(k) for k in scn['knoll_specs']],
                       grass={k:{key:value for key,value in v.items() if isinstance(value,(bool,int,float,str))}
                              for k,v in scn['grass'].items() if isinstance(v,dict)},
                       cliff_outline=D.__dict__.get('postcard_outline', []),
                       strata_stats=D.__dict__.get('strata_stats', []),
                       strata_kwargs=D.__dict__.get('strata_kwargs', {})),handle,indent=2)
    print('HOLE09 UNVERIFIED checkpoint '+checkpoint,flush=True)
batch_stats = HL.merge_static_scenery(D, scn)                  # static masonry only; complete stone interiors/material slots and every plant pivot remain intact
compound_stats=HL.merge_shared_tuft_clumps(D,scn)
print('[hole09] actual shared clumps', {k:v for k,v in compound_stats.items() if k!='groups'},flush=True)
bpy.context.view_layer.update()


def tee_parallax_uvs(D):
    """REPAIR ROUND 3 (review: 'a faint straight ruler line crosses the whole tee frame where the grass shade steps', Game-view rows 556 / 557 of hole09_1_tee.png, the far edge of the tee box). The tee box is a
    flat plate 10 cm over the fairway (scoring: heights frozen) with no riser: the address camera (CameraRig.FrameAddress: 4.5 yd behind the ball, 2.46 yd above the tee top, 11.9 deg down at the far edge) cannot see the
    0.48 m of fairway just behind the edge, so the picture jumps from the plate's texture to the fairway's texture 0.48 m further on, although both carry the same world function (measured by
    tools/tee_parallax_check.py: a 0.49 m texture jump on 15 of 15 camera rays; the Blender preview row step 3.29 levels against 1.84 for the other rows). The plate's UVs are now the fairway's centerline UV of the
    point p + k (p - c): the plate texture scaled by k = 0.1 m / 2.25 m = 4.4 % about the address camera c, which is exactly the ground the plate hides from c (a ray that grazes the edge at height 0.1 over the fairway
    lands 0.1 / tan(elevation) = 0.1 |p - c| / 2.25 m further on, along the ray). The ball sits on the plate and the texture is smooth, so nothing else shows. Only UV data of the TEE_BOX changes (vertices, faces,
    heights, outline untouched); its UVs stay a smooth centerline function."""
    ob = bpy.data.objects["TEE_BOX"]
    me = ob.data
    cl = L.CenterlineParam(D)
    c0 = np.array(P.m(*D.hole.center[0]), float)
    c1 = np.array(P.m(*D.hole.center[1]), float)
    dirv = (c1 - c0) / np.linalg.norm(c1 - c0)
    mw = np.array(ob.matrix_world)
    X = np.array([mw[:3, :3] @ np.array(me.vertices[lp.vertex_index].co) + mw[:3, 3] for lp in me.loops])
    fw = bpy.data.objects["FAIRWAY"]
    plate = float(X[:, 2].max()) - float(max(v.co.z for v in fw.data.vertices))          # 0.10 m: tee top over the fairway
    cam = c0 - dirv * TEE_CAM_BACK_YD * P.YD                                               # the address camera, in plan
    hc = TEE_CAM_UP_YD * P.YD                                                              # its height over the tee top
    k = plate / hc
    pts = X[:, :2] + (X[:, :2] - cam[None, :]) * k
    uu, vv = cl.uv(pts[:, 0], pts[:, 1])
    tile = L.LOOK["LK_FAIRWAY"][2]
    uu, vv = uu / tile, vv / tile
    vv -= np.round(np.mean(vv))
    lay = me.uv_layers.active
    lay.data.foreach_set("uv", np.stack([uu, vv], 1).ravel())
    me.update()
    return plate, k, float(np.abs((X[:, :2] - cam[None, :]) * k).max())


tee_shift = tee_parallax_uvs(D)
# REPAIR ROUND 1 (finding 'island reads flat: no darker fringe / rough at the sides of the near ground'): the visible part of FAIRWAY_FIRSTCUT is the 3 yd collar of ROUGH LIE round the fairway (the fairway lie is under
# the FAIRWAY mesh, 6 cm higher), so it takes the rough material: the mown ribbon is bounded by darker rough like split.jpg. The material is swapped AFTER assign_uvs: the collar keeps its CENTERLINE UVs (smooth over the
# long n-gons of that mesh; planar+warp UVs of LK_ROUGH streak across them) at the fairway tile (10 m, 1.2 x the rough contract density: UV_DENSITY allows 1/3 .. 3 x). Vertices / faces / heights untouched.
bpy.data.objects["FAIRWAY_FIRSTCUT"].data.materials[0] = L.look_material("LK_ROUGH", D)
firstcut_uv_faces = HL.repair_firstcut_uvs(D)                 # shading only: nonlinear warp smeared11 large frozen triangles; world-planar mapping keeps exact geometry

ok, detail = L.compare_ground(D, snap)
gate("H_PLAY_UNCHANGED_INBUILD", ok, "play surfaces vs the snapshot taken before any look code: " + detail)
if QA:
    for name, ok_, detail in L.audit_look(D) + L.v2_gates(D, pockets=L.sea_pockets(D, None)):
        gate(name, ok_, detail)
    tort = L.skin_tortuosity(D)
    gate("SKIN_JAGGED", tort is not None and tort >= 1.15, f"strata skin mid-row plan tortuosity {tort} (>= 1.15; the v1 skin measured 1.03; 1.000 = a smooth curtain)")

st = P.stats(D)
if OUT:
    # Evidence reflects this build's actual geometry, never a budget estimate.
    info = dict(stats=st, gates=[dict(name=n,ok=k,detail=d) for n,k,d in GATES],
                masonry_batches=batch_stats, shared_tuft_clumps=compound_stats, cliff_outline=D.__dict__.get('postcard_outline', []),
                strata_stats=D.__dict__.get('strata_stats', []),
                ridge_specs=[list(k) for k in scn['knoll_specs']],
                grass={k:{key:value for key,value in v.items() if isinstance(value,(bool,int,float,str))}
                       for k,v in scn['grass'].items() if isinstance(v,dict)},
                plant_counts={k:len(scn[k]) for k in ('shrubs','shrubs_out','agave','flowers','tufts')})
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT,'phase3_build.json'),'w') as handle:
        json.dump(info,handle,indent=2)
print(f"HOLE09 stats: {st['objects']} objects, {st['meshes']} meshes, {st['tris']} tris ({st['ground_tris']} ground); "
      f"scrub faces {n_scrub}; build {time.time() - t_start:.0f}s", flush=True)

if RENDER:
    P.render_overview(D, res=frame_overview(D))
# save like P.save but WITHOUT relative_remap (the proof pass of round 2, work/postcard-look/v2/proof/PROOF.md: LK_TEXTURED@blend failed on the INSTALLED blender/hole_09.blend because the paths were remapped relative to
# the staging folder): the LK_* image paths stay the absolute Unity/Assets/Resources/Course/Look/*.png paths they were loaded with, so the .blend finds its textures from the staging folder AND after the copy
# to blender/hole_09.blend (hole08_build.py / hole10_build.py already do this)
blend = P._blend_path(D)
P._guard_target(D, blend)
os.makedirs(os.path.dirname(blend), exist_ok=True)
bpy.ops.wm.save_as_mainfile(filepath=blend, relative_remap=False)
fbx = L.export_look_fbx(D)
print(f"HOLE09 wrote {blend} and {fbx} ({os.path.getsize(fbx) / 1048576:.2f} MB)", flush=True)
fails = [n for n, ok_, _ in GATES if not ok_]
print(f"HOLE09 in-build gates: {len(GATES)} run, {len(fails)} FAIL {fails}", flush=True)
