const {chromium}=require('/Users/adnanyonathan/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path');
(async()=>{const root=__dirname;const screens=JSON.parse(fs.readFileSync(path.join(root,'screens.json')));const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1280,height:720},deviceScaleFactor:1});let errors=[];page.on('pageerror',e=>errors.push(String(e)));
for(let i=0;i<screens.length;i++){await page.goto('file://'+path.join(root,'index.html')+'?capture='+i);await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(root,'screens',screens[i].id+'.png')});}
const cards=screens.map(s=>`<article><img src="screens/${s.id}.png"><h3>${s.id} / ${s.title}</h3><p>${s.note}</p></article>`).join('');fs.writeFileSync(path.join(root,'all-screens.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><title>All UI examples</title><link rel="stylesheet" href="style.css"><body><header class="review"><h1>Island Sports Club / UI examples</h1><a href="index.html">Open interactive review →</a></header><div class="gallery">${cards}</div></body></html>`);
await page.setViewportSize({width:1600,height:1000});await page.goto('file://'+path.join(root,'all-screens.html'));await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(root,'all-screens.png'),fullPage:true});
const pick=[0,1,6,7,13,17];fs.writeFileSync(path.join(root,'review-sheet.html'),`<!doctype html><html><meta charset="utf-8"><link rel="stylesheet" href="style.css"><body><header class="review"><h1>WEEKEND SPORTS CLUB / UI DIRECTION 01</h1><span>Editable studies · actual court backdrop</span></header><div class="gallery">${pick.map(i=>`<article><img src="screens/${screens[i].id}.png"><h3>${screens[i].title}</h3></article>`).join('')}</div></body></html>`);await page.goto('file://'+path.join(root,'review-sheet.html'));await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(root,'review-sheet.png'),fullPage:true});
// Export transparent UI primitives for review/runtime prototyping; keep SVG source.
const sharp=require('/Users/adnanyonathan/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');for(const f of fs.readdirSync(path.join(root,'assets')).filter(f=>f.endsWith('.svg')))await sharp(path.join(root,'assets',f)).resize({width:f.startsWith('icon')?256:undefined}).png().toFile(path.join(root,'assets',f.replace('.svg','.png')));
console.log(JSON.stringify({screens:screens.length,browserErrors:errors}));await browser.close();})();
