const screensV4=[['home','Home · copy updated'],['sports','Sport menu · copy updated'],['loading','Loading · practice swings'],['flyover','Venue intro'],['rally','Gameplay HUD'],['scorefocus','Scorebug detail'],['point','Point won'],['pause','Pause'],['results','Results']];
const hud=(p1='30',p2='15',status='ADNAN SERVING')=>`<div class="hud-score"><div class="hud-title"><span>TROPICAL OPEN</span><i></i></div><div class="hud-columns"><span>SINGLES</span><span>GAMES</span><span>POINTS</span></div><div class="hud-row"><div class="hud-name"><i class="serving"></i> ADNAN</div><div class="hud-game">2</div><div class="hud-point">${p1}</div></div><div class="hud-row other"><div class="hud-name"><i style="width:8px"></i>RILEY</div><div class="hud-game">1</div><div class="hud-point">${p2}</div></div><div class="hud-status"><span>SET 1</span><strong>${status}</strong></div></div>`;
const control=(s,alt=false)=>`<button class="refined-button ${alt?'secondary':''}">${s}<span>→</span></button>`;
const court='<img class="bg" src="assets/gameplay.png">';
const pauseControl='<button class="hud-pause" aria-label="Pause match">Ⅱ</button>';
function renderV4(s){if(s==='home'||s==='sports'){return menuRender('toybox',s).replace('GOOD TIMES.<br><em>GREAT GAMES.</em>','ISLAND<br><em>SPORTS CLUB</em>').replace('LET’S PLAY','PLAY').replace('Your locker','Locker').replace('☀ Your island. Your game.','').replace('WHAT’S THE <em>GAME?</em>','SELECT A <em>SPORT</em>').replace('Head out for a round.','Play a round').replace('Pick a sport on your phone','Select a sport on your phone').replace('YOUR ATHLETE','PLAYER').replace('state-home','state-home menu-copy');}
let b='';
if(s==='loading')b=`<div class="practice-actor"><img id="practiceFrame" src="assets/swings/00.png" style="width:100%;height:100%"></div><div class="load-title"><div class="meta-label">TENNIS / EXHIBITION</div><h1 class="new-title" style="margin:13px 0">Tropical Open</h1><p class="new-sub">One set · Singles</p></div><div class="practice-instructions"><div class="meta-label">WARM-UP</div><h2>Practice your swing</h2><p class="new-sub">Swing your phone to practice.<br>You can swing as often as you like.</p><div class="input-chip">↗ &nbsp; Practice only · No score</div></div><div class="warmup-wave"></div><div class="load-bottom"><div class="top"><span id="loadStatus">Loading match…</span><strong id="loadPercent">72%</strong></div><div class="thin-progress"><i></i></div></div>`;
if(s==='flyover')b=`<img class="bg" src="assets/flyover.png"><div class="new-venue"><div class="venue-tag">05</div><div class="venue-copy"><div class="meta-label">ISLAND CIRCUIT</div><h1>Tropical Open</h1><div class="small-note">Singles · One set</div></div></div><div style="position:absolute;right:64px;bottom:64px;width:175px">${control('Skip intro',true)}</div>`;
if(s==='rally')b=court+hud()+pauseControl+`<div class="shot-readout"><i class="shot-marker"></i><div><strong>PERFECT</strong><span>Forehand</span></div><div class="shot-speed">118<small>KM/H</small></div></div>`;
if(s==='scorefocus')b=`<div style="position:absolute;top:58px;left:90px"><div class="meta-label">TOYBOX / GAMEPLAY SYSTEM</div><h1 class="new-title" style="font-size:44px;margin-top:12px">Match score</h1></div><div class="scoresheet">${hud()}</div><div class="caption-panel"><div class="meta-label">DESIGN DETAIL</div><h2>Score first.</h2><p>Separate columns for games and points. Stable tabular numerals. A small serving indicator. A quiet frame with a blue edge.</p><h2 style="margin-top:35px">State changes</h2><div class="row"><span class="pill">DEUCE</span><span class="pill">ADVANTAGE</span></div><p style="margin-top:18px">The same grid handles 40–40, AD and tiebreak points. Names never compete with the score.</p></div><div style="position:absolute;bottom:90px;left:92px"><div class="meta-label">DEUCE / SECOND STATE</div><div style="position:relative;margin-top:16px;transform:scale(.65);transform-origin:top left">${hud('40','40','DEUCE')}</div></div>`;
if(s==='point')b=court+hud('40','15','POINT ADNAN')+pauseControl+`<div class="point-card"><div class="meta-label">WINNER</div><h2>Point Adnan</h2><strong>40 — 15</strong></div>`;
if(s==='pause')b=court+hud()+`<div class="veil"></div><div class="refined-panel modal"><div class="meta-label">TROPICAL OPEN</div><h2 class="new-title" style="font-size:48px;text-transform:none">Paused</h2><div class="stack">${control('Resume')}${control('Settings',true)}${control('Main Menu',true)}</div></div>`;
if(s==='results')b=`<div style="position:absolute;left:64px;top:55px"><div class="meta-label">TROPICAL OPEN / FINAL RESULT</div><h1 class="new-title" style="margin-top:22px;font-size:66px">Match won</h1><p class="new-sub" style="margin-top:14px">Adnan defeats Riley</p><div style="font:700 102px Arial;color:#183d88;letter-spacing:-6px;margin:20px 0 28px">6 — 4</div><div class="row"><div class="stat-chip"><b>12</b><span>Perfect shots</span></div><div class="stat-chip"><b>18</b><span>Longest rally</span></div></div><div class="stack" style="margin-top:32px;width:430px">${control('Next round')}<div class="row">${control('Rematch',true)}${control('Main Menu',true)}</div></div><div class="small-note" style="margin-top:20px">Select an action on your phone.</div></div><div style="position:absolute;right:50px;top:70px;width:510px;height:530px;background:#7ec6de;border-radius:110px 110px 38px 38px;overflow:hidden;border:2px solid white;box-shadow:0 9px 0 #b1c5e6,0 24px 45px #163f8120"><img src="assets/hero.png" style="width:100%;height:100%;object-fit:cover"><div style="position:absolute;bottom:20px;left:30px;right:30px;text-align:center;background:#ffffffed;border-radius:14px;padding:14px;color:#234786;font:700 18px Arial">ADNAN</div></div>`;
return `<div class="frame refined state-${s} ${s==='loading'?'load-scene':''}">${b}</div>`;}
let active=Number(new URLSearchParams(location.search).get('screen')||4),timer=null,queued=false,playing=false,count=0,ready=false;
const imgCache=Array.from({length:60},(_,i)=>{const im=new Image();im.src=`assets/swings/${String(i).padStart(2,'0')}.png`;return im});
function practiceSwing(){if(active!==2)return;if(playing){queued=true;return;}playing=true;count++;document.querySelector('.frame').classList.add('swinging');let f=0;const update=()=>{const im=document.getElementById('practiceFrame');if(!im)return;im.src=imgCache[f].src;f++;if(f>=60){playing=false;clearInterval(timer);document.querySelector('.frame')?.classList.remove('swinging');document.getElementById('practiceCount').textContent=`Practice swings: ${count}`;if(ready){document.getElementById('loadStatus').textContent='Ready';document.getElementById('loadPercent').textContent='100%';document.querySelector('.thin-progress i').style.width='100%';queued=false;setTimeout(()=>showV4(3),300);}else if(queued){queued=false;practiceSwing();}}};update();timer=setInterval(update,1000/15);}
function showV4(i){clearInterval(timer);timer=null;playing=false;queued=false;ready=false;active=i;document.querySelector('.stage').innerHTML=renderV4(screensV4[i][0]);document.querySelectorAll('#states button').forEach((b,k)=>b.setAttribute('aria-pressed',k===i));document.querySelector('.demo-tools').style.display=i===2?'flex':'none';document.querySelector('.caption').textContent=screensV4[i][1]+'. Review prototype only. Serve meter is excluded and unchanged. Menu geometry/materials are retained; menu words are updated.';if(i===0||i===1){document.querySelectorAll('.frame button').forEach(b=>b.onclick=()=>showV4(i===0?1:2));}}
screensV4.forEach((x,i)=>{const b=document.createElement('button');b.textContent=x[1];b.onclick=()=>showV4(i);document.getElementById('states').append(b)});document.getElementById('practiceButton').onclick=practiceSwing;document.getElementById('readyButton').onclick=()=>{if(active!==2)return;ready=true;if(!playing){document.getElementById('loadStatus').textContent='Ready';document.getElementById('loadPercent').textContent='100%';document.querySelector('.thin-progress i').style.width='100%';setTimeout(()=>showV4(3),300)}};
addEventListener('keydown',e=>{if(e.code==='Space'&&active===2&&!e.repeat){e.preventDefault();practiceSwing();}});const capture=new URLSearchParams(location.search).has('capture');if(capture)document.body.className='capture';function fitV4(){if(!capture)document.querySelector('.stage').style.zoom=Math.min(1,(innerWidth-40)/1280);}showV4(active);fitV4();addEventListener('resize',fitV4);
